import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  // Generated by Next on every build, and not ours to edit.
  { ignores: [".next/**", "node_modules/**", "next-env.d.ts"] },
  // The custom-font rule targets the pages router's _document; App Router
  // loads fonts from the layout's <head>, which is the supported place.
  { files: ["src/app/layout.tsx"], rules: { "@next/next/no-page-custom-font": "off" } },
];

export default config;
