import coreWebVitals from "eslint-config-next/core-web-vitals";
import typescript from "eslint-config-next/typescript";

const config = [
  ...coreWebVitals,
  ...typescript,
  // Generated by Next on every build, and not ours to edit.
  { ignores: [".next/**", "node_modules/**", "next-env.d.ts"] },
  // The custom-font rule targets the pages router's _document. The App Router
  // loads fonts from the layout's head, which is the supported place.
  { files: ["src/app/layout.tsx"], rules: { "@next/next/no-page-custom-font": "off" } },
];

export default config;
